/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface BimplusLanguageMenu {
    /**
    * -------------------------------------------------------------------------- properties --------------------------------------------------------------------------
    */
    'selectedLanguage': string;
  }
  interface BimplusLanguageMenuAttributes extends StencilHTMLAttributes {
    /**
    * -------------------------------------------------------------------------- language selected event --------------------------------------------------------------------------
    */
    'onBimplusLanguageSelected'?: (event: CustomEvent<string>) => void;
    /**
    * -------------------------------------------------------------------------- properties --------------------------------------------------------------------------
    */
    'selectedLanguage'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BimplusLanguageMenu': Components.BimplusLanguageMenu;
  }

  interface StencilIntrinsicElements {
    'bimplus-language-menu': Components.BimplusLanguageMenuAttributes;
  }


  interface HTMLBimplusLanguageMenuElement extends Components.BimplusLanguageMenu, HTMLStencilElement {}
  var HTMLBimplusLanguageMenuElement: {
    prototype: HTMLBimplusLanguageMenuElement;
    new (): HTMLBimplusLanguageMenuElement;
  };

  interface HTMLElementTagNameMap {
    'bimplus-language-menu': HTMLBimplusLanguageMenuElement
  }

  interface ElementTagNameMap {
    'bimplus-language-menu': HTMLBimplusLanguageMenuElement;
  }


}
